### PR TITLE
Add RoundHalfToZero and RoundHalfFromZero rounding strategies

### PR DESCRIPTION
**Pull request by ababkin**
This adds to following new rounding strategies:
https://en.wikipedia.org/wiki/Rounding#Round_half_towards_zero
https://en.wikipedia.org/wiki/Rounding#Round_half_away_from_zero

please refer to https://github.com/fpco/safe-decimal/issues/6 for discussion and details

### CODE REVIEW

**Comment by lehins** [comment]
I think this PR is missing some commits :wink:

**Comment by ababkin** [comment]
@lehins - ok it should be ready except I cannot easily figure out how to change the `roundHalfToZeroTo` in order for the prop tests to pass. (the rounding is working correctly but the test is wrong). If you have a second to take a look I'm sure you will see what causes it instantly.

**Comment by ababkin** [comment]
@lehins - any help on the above? (`roundHalfFromZeroTo`) I cannot seem to figure it out. I'm leveraging your testing code that you had commented out. It seems to have worked for `roundHalfToZeroTo` but not `roundHalfFromZeroTo` with the `r >= 5` -> `r > 5` change to reverse rounding direction.

**Comment by lehins** [comment]
Looks like implementation was correct, but the test case was not accounting for the remainder: `roundHalfToZero 0.501` equals  `1` not `0`. I pushed the fix for it.

I'll take a more thorough look next week and will merge it. But skimming through the PR right now looks great.

**Comment by symbiont-alexey-babkin** [comment]
awesome! waiting for the merge to start using this on my end.

**Comment by lehins** [comment]
@ababkin  Thank you for your contribution :+1:

**Pull request merged**
